name: Library Build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
  pull_request:
    branches: [main]
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      - run: dotnet restore
      - run: dotnet build Navs.slnx --configuration Release --no-restore
      - run: dotnet test Navs.slnx --no-restore
