name: Library Build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dotnet 9.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet restore
      - run: dotnet build Navs.sln -f net9.0 --configuration Release --no-restore
      - run: dotnet test Navs.sln -f net9.0 --no-restore
  build8:
    runs-on: ubuntu-latest
    name: Build dotnet 8.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet restore
      - run: dotnet build Navs.sln -f net8.0 --configuration Release --no-restore
      - run: dotnet test Navs.sln -f net8.0 --no-restore
