name: Samples Build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
      - tests/**
      - samples/**
  pull_request:
    branches:
      - main
      - dev
    paths:
      - src/**
      - samples/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dotnet 9.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet restore samples/Samples.sln
      - run: dotnet build samples/Samples.sln -f net9.0 --configuration Release --no-restore
