name: Samples Build

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - samples/**
  pull_request:
    branches: [main]
    paths:
      - src/**
      - samples/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dotnet 8.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet restore
      - run: dotnet build samples/Samples.sln -f net8.0 --configuration Release --no-restore
  buildnet6:
    runs-on: ubuntu-latest
    name: Build dotnet 6.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
      - run: dotnet restore
      - run: dotnet build samples/Samples.sln -f net6.0 --configuration Release --no-restore
